owner: HPCSLab # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Web Page
    url: https://www.hpcs.cs.tsukuba.ac.jp
  - name: Internal Page
    url: https://www.hpcs.cs.tsukuba.ac.jp/internal/pukiwiki/
    headers:
      - "Authorization: Basic $AUTH_BASIC"
  - name: Webmail
    url: https://mail.hpcs.cs.tsukuba.ac.jp
    headers:
      - "Authorization: Basic $AUTH_BASIC"
#  - name: Auth Server httpd
#    url: https://auth.hpcs.cs.tsukuba.ac.jp
#    __dangerous__insecure: true
#    expectedStatusCodes:
#      - 403
  - name: Mail (SMTP)
    url: mail.hpcs.cs.tsukuba.ac.jp
    port: 25
    check: "tcp-ping"
  - name: Mail (SMTPS)
    url: mail.hpcs.cs.tsukuba.ac.jp
    port: 465
    check: "tcp-ping"
# IMAP is disabled now
#  - name: Mail (IMAP)
#    url: mail.hpcs.cs.tsukuba.ac.jp
#    port: 143
#    check: "tcp-ping"
  - name: Mail (IMAPS)
    url: mail.hpcs.cs.tsukuba.ac.jp
    port: 993
    check: "tcp-ping"
  - name: Mail (POP3)
    url: mail.hpcs.cs.tsukuba.ac.jp
    port: 110
    check: "tcp-ping"
  - name: Mail (POP3S)
    url: mail.hpcs.cs.tsukuba.ac.jp
    port: 995
    check: "tcp-ping"
  - name: External DNS
    url: dns.hpcs.cs.tsukuba.ac.jp
    port: 53
    check: "tcp-ping"
  - name: Work SSH
    url: work.hpcs.cs.tsukuba.ac.jp
    port: 22
    check: "tcp-ping"

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HPCS Status Page
  introTitle: HPCS Status Page
  introMessage: HPCSの基幹系の死活監視をします
  navbar:
    - title: Status
      href: /$REPO/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: HPCSLab
      href: https://www.hpcs.cs.tsukuba.ac.jp/

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
